# local 개발환경
# h2 database

spring:
  h2.console.enabled: true
  datasource:
    platform: h2
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./tmp/h2/h2database;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa.hibernate:
    ddl-auto: create-drop

logging:
  file: logs/boot_blog-local.log
  level:
    com.ex2i: DEBUG